Hw 1
clockbel/Java-Tinkoff-2 pull request #1
Opened 2024-02-12 19:00 UTC by clockbel

2024-02-21 20:45 UTC, strelchm requested changes

2024-02-21 20:45 UTC, strelchm commented on bot/src/main/java/edu/java/bot/model/command_utils/CommandStatus.java
> +public final class CommandStatus {
Название класса неочевидное - понимается статус команды, что-то вроде энума. Почему бы не делать в **BotController** эти действия, если мы будем доп классы в BotController инжектить, то будем добавлять аргументы в методе?

2024-02-21 20:45 UTC, strelchm commented on bot/src/main/java/edu/java/bot/model/command_utils/checks/CheckTrack.java
> +        boolean check = true;
В 
`return urlList.contains(url);
`можно ли упростить? Либо здесь еще логика будет?

2024-02-21 20:45 UTC, strelchm commented on bot/src/main/java/edu/java/bot/controller/BotController.java
> +@Controller
**nit:** Аннотация **@Controller** больше относится к [MVC ](https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-controller.html)- т е к обработке http-запросов от пользователей / доп обработка, например, ошибок. Предлагаю здесь сделать **@Component** - т е определенный бин с бизнес-логикой, что будет больше подходить для листенера Telegram

2024-02-21 20:45 UTC, strelchm commented on bot/src/main/java/edu/java/bot/model/command_utils/checks/CheckTrack.java
> +public final class CheckTrack {
**nit:** геттеры, сеттеры и конструктор можно заменить аннотациями lombok @Getter @Setter @NoArgsContructor и т. д.

2024-02-21 20:45 UTC, strelchm commented on bot/src/main/java/edu/java/bot/model/command_utils/commands/Commands.java
> +    public static Map<String, Command> commands() {
Здесь, если верно понял, для **HelpCommand**, создаем лишние объекты, хотя у нас бины создаются в тоже время. Возможно, можем в **HelpCommand** заинжектить другие команды

2024-02-21 20:45 UTC, strelchm commented on bot/src/main/java/edu/java/bot/model/command_utils/commands/Commands.java
> +    public static Map<String, Command> commands() {
Например, используя [@Qualifier](https://www.baeldung.com/spring-injecting-collections#qualifier)

2024-02-23 11:34 UTC, clockbel commented on bot/src/main/java/edu/java/bot/model/command_utils/commands/Commands.java
> +    public static Map<String, Command> commands() {
Перевел на @Qualifier, но не добавляется в Map<String, Command> не добавляется HelpCommand. Я могу внести данные о команде вручную (stringBuilder + command()+description())?

2024-02-23 11:42 UTC, clockbel commented on bot/src/main/java/edu/java/bot/model/command_utils/checks/CheckTrack.java
> +public final class CheckTrack {
Здесь не совсем понятно к чему это сообщение. Может вы имели ввиду класс User, а не CheckTrack?

2024-02-23 12:15 UTC, strelchm commented on bot/src/main/java/edu/java/bot/model/command_utils/checks/CheckTrack.java
> +public final class CheckTrack {
Да, похоже что в User, здесь приватный конструктор. Так посмотрел, геттеры - сеттеры используешь аннотациями, вроде все нормально

2024-02-23 12:17 UTC, strelchm commented on bot/src/main/java/edu/java/bot/model/command_utils/commands/Commands.java
> +    public static Map<String, Command> commands() {
Думаю да, т к не попадает в Qualifier, нормально

2024-02-24 21:28 UTC, strelchm approved these changes

2024-02-24 22:20 UTC, merged