hw2
clockbel/Java-Tinkoff-2 pull request #2
Opened 2024-02-16 17:17 UTC by clockbel

2024-02-28 20:37 UTC, strelchm requested changes

2024-02-28 20:37 UTC, strelchm commented on scrapper/src/main/java/edu/java/response/github/RepositoryResponse.java
> +    @JsonProperty("full_name")
Если у нас все DTO в camel_case, возможно, необходимо установить сериализацию/десериализацию в пропертях и убрать @JsonProperty:
```
spring.jackson.property-naming-strategy=SNAKE_CASE
```
Либо если отличается какое-то DTO, то над классом правило устанавливать:
```
@JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy.class)
```

2024-02-28 20:37 UTC, strelchm commented on scrapper/src/main/java/edu/java/response/stackoverflow/QuestionResponse.java
> +        @JsonIgnore
Данное поле не используется, но видимо добавлено сюда в связи с **com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException**. Предлагаю убрать поле и добавить над классом 
```
@JsonIgnoreProperties(ignoreUnknown = true)
```
Подробнее [см.
](https://www.baeldung.com/jackson-deserialize-json-unknown-properties)

2024-02-28 20:37 UTC, strelchm commented on scrapper/src/main/java/edu/java/ScrapperApplication.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(ScrapperApplication.class);
Зачем здесь логгер

2024-02-28 20:37 UTC, strelchm commented on scrapper/src/test/java/edu/java/scrapper/client/GitHubClientTest.java
> +import java.time.OffsetDateTime;
nit: не используется

2024-02-28 20:37 UTC, strelchm commented on scrapper/src/main/java/edu/java/response/github/RepositoryResponse.java
> +package edu.java.response.github;
Возможно, пакет сделать edu.java.dto.response.github добавив "**dto**", на случай, если у нас так же подпакет request будет

2024-02-29 08:37 UTC, clockbel commented on scrapper/src/main/java/edu/java/response/github/RepositoryResponse.java
> +    @JsonProperty("full_name")
Столкнулся с проблемой: попытался использовать spring.jackson.property-naming-strategy=SNAKE_CASE, но код не видит его. В интернете нашел способ подключить следующим образом: spring.jackson.property-naming-strategy=com.fasterxml.jackson.databind.PropertyNamingStrategy.SnakeCaseStrategy, но и его он не видит. Могу в рамках этого проекта использовать @JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy.class)?

2024-02-29 09:04 UTC, strelchm commented on scrapper/src/main/java/edu/java/response/github/RepositoryResponse.java
> +    @JsonProperty("full_name")
Да, вполне нормально @JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy.class)

2024-02-29 09:08 UTC, strelchm commented on scrapper/src/main/java/edu/java/response/github/RepositoryResponse.java
> +    @JsonProperty("full_name")
По идее, [должно заработать](https://www.baeldung.com/spring-webclient-json-custom-deserialization#custom-deserialization-using-global-config), если в ClientConfiguration добавить бин, в который инжектить маппер
```
.@Bean
public CodecCustomizer codecCustomizer(ObjectMapper objectMapper) {
    return configurer -> {
      MimeType mimeType = MimeType.valueOf(MediaType.APPLICATION_JSON_VALUE);
      CodecConfigurer.CustomCodecs customCodecs = configurer.customCodecs();
      customCodecs.register(new Jackson2JsonDecoder(customObjectMapper, mimeType));
      customCodecs.register(new Jackson2JsonEncoder(customObjectMapper, mimeType));
    };
}
```

2024-02-29 10:18 UTC, strelchm commented on scrapper/src/main/java/edu/java/configuration/ClientConfiguration.java
> +        return new GitHubClient(WebClient.builder().baseUrl(applicationConfig.gitHubBaseUrl()).build());
Отсутсвует:

> При создании клиента обязательно должна быть возможность указать базовый URL. При этом если он не указывается, то должен использоваться URL по умолчанию.

2024-02-29 10:24 UTC, clockbel commented on scrapper/src/main/java/edu/java/configuration/ClientConfiguration.java
> +        return new GitHubClient(WebClient.builder().baseUrl(applicationConfig.gitHubBaseUrl()).build());
![image](https://github.com/clockbel/Java-Tinkoff-2/assets/135724798/1f9d144a-3529-462e-a4e8-a95ac93aecef)
Вот здесь у меня указывается базовый URL. Это не считается выполнением данного пункта? Потому что я использовал конструкцию которую привели в чате
![image](https://github.com/clockbel/Java-Tinkoff-2/assets/135724798/ad868a88-cc1b-4edd-a06c-e18070754aba)

2024-02-29 10:33 UTC, clockbel commented on scrapper/src/main/java/edu/java/configuration/ClientConfiguration.java
> +        return new GitHubClient(WebClient.builder().baseUrl(applicationConfig.gitHubBaseUrl()).build());
Кажись я понял что необходимо делать, надо создать в Client метод create и уже там передавать базовый URL, сейчас исправлю

2024-02-29 11:01 UTC, clockbel commented on scrapper/src/main/java/edu/java/configuration/ClientConfiguration.java
> +        return new GitHubClient(WebClient.builder().baseUrl(applicationConfig.gitHubBaseUrl()).build());
Исправил Clients таким образом, что можно указать базовый URL

2024-02-29 11:24 UTC, strelchm commented on scrapper/src/main/java/edu/java/configuration/ClientConfiguration.java
> +        return new GitHubClient(WebClient.builder().baseUrl(applicationConfig.gitHubBaseUrl()).build());
Здесь имел ввиду, что базовый URI передаете, но по-умолчанию нету
![image](https://github.com/clockbel/Java-Tinkoff-2/assets/23243577/70981bbe-d6c1-40db-8a9f-fd42a31a0d66)
Я бы здесь сделал бы 
```
baseUrl == null ? DEFAULT_URI : baseUrl
```
т е если не задали в конфигах базовый URI, то берем зашитый дефолтный

2024-02-29 11:27 UTC, strelchm commented on scrapper/src/main/java/edu/java/configuration/ClientConfiguration.java
> +        return new GitHubClient(WebClient.builder().baseUrl(applicationConfig.gitHubBaseUrl()).build());
> Исправил Clients таким образом, что можно указать базовый URL

да, так стало лучше - в самом клиенте конфигурируем, в том числе там мы URI можем некоторым образом поменять, либо базовые настройки

2024-02-29 11:29 UTC, strelchm commented on scrapper/src/main/java/edu/java/configuration/ClientConfiguration.java
> +        return new GitHubClient(WebClient.builder().baseUrl(applicationConfig.gitHubBaseUrl()).build());
Проверки на @NotNull нету пропертей конфигов, добавление дефолтного URI кажется норм решением. Либо тогда валидацию добавить в конфигах, что бы проперти обязательными были
![image](https://github.com/clockbel/Java-Tinkoff-2/assets/23243577/cba376ac-2cd0-4649-bf1e-1e9a3e1d631b)

2024-02-29 17:45 UTC, clockbel commented on scrapper/src/main/java/edu/java/configuration/ClientConfiguration.java
> +        return new GitHubClient(WebClient.builder().baseUrl(applicationConfig.gitHubBaseUrl()).build());
Сделал обработку на то, чтобы выбирался DEFAULT_URI , если будет введен null

2024-02-29 22:06 UTC, strelchm approved these changes

2024-03-01 05:49 UTC, merged